### ISSUE TITLE
emacs daemon not work on Windows

### ISSUE THREAD

**Issue by saccohuo** [coldnew/hexo-renderer-org#19]
I try the new version, and find it will start a new emacs window when `hexo g`.
I think it maybe the reason is that there is no available emacs daemon for Windows, so the method to connect to emacs with daemon will not work on Windows.

**Comment by coldnew** [comment]
@saccohuo  wait, you mean `emacs server` not work on windows ?

I can add old version method (start multi emacs process to render page) if you need, but I think use emacs server can speed up renderer speed so it's more prefered.

**Comment by saccohuo** [comment]
Emacs supports server on Windows which is different with daemon on Linux or macOS.
On Windows, server-mode should be required to support emacs server.

**Comment by saccohuo** [comment]
I wanna know if you can fix this problem as soon as possible, because I cannot update my blog since updating to the new version.
Thanks for that.

**Comment by coldnew** [comment]
I think it'll be done today or tomorrow :)

**Comment by coldnew** [comment]
I add an experimental emacs process renderer support, hope it can solve current problem
just use following in your `_config.yml`

```yaml
org:
      emacs: 'YOUR EMACS PATH'
      daemonize: false
      line_number: true
```

**Comment by saccohuo** [comment]
The emacs daemon problem is solved.
However, when I `hexo g`, the content of every post is empty except the index.html.
I do not know if there is something wrong in my `config.yml`.
```
org:
  emacs: C:/emacs/bin/emacs.exe
  emacsclient: C:/emacs/bin/emacsclient.exe
  # emacs: '/cygdrive/c/emacs/bin/emacs.exe'
  # emacsclient: '/cygdrive/c/emacs/bin/emacsclient.exe'
  # emacs: 'emacs'
  # emacsclient: 'emacsclient'
  daemonize: false
  common: |
          #+OPTIONS: toc:nil num:nil
          #+BIND: org-html-postamble \"Last Updated %C.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"
  cachedir: './hexo-org-cache/'
  theme: 'tango-dark'
  user_config: './emacs/init.el'
  clean_cache: true
  htmlize: true
  line_number: true
  debug: true
```

**Comment by coldnew** [comment]
Not sure what's wrong :(

I think you config can be minified as following:

```yaml
org:
  emacs: C:/emacs/bin/emacs.exe
  emacsclient: C:/emacs/bin/emacsclient.exe
  daemonize: false
  line_number: true
  common: |
          #+OPTIONS: toc:nil num:nil
          #+BIND: org-html-postamble \"Last Updated %C.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"
```

If you still have problem, can you try https://github.com/coldnew/hexo-org-example/tree/test-daemonize is working on your system or not ?

```
git clone https://github.com/coldnew/hexo-org-example.git -b test-daemonize
```

This branch is what I use for testing emacs process method.
