### ISSUE TITLE
"hexo g" but get "UnhandledPromiseRejectionWarning" and "TypeError" on Windows

### ISSUE THREAD

**Issue by saccohuo** [coldnew/hexo-renderer-org#3]
I run "hexo g" and get the following error.
Environment: Windows 7 x64, node v6.10.0, npm v3.10.10, python 3.6.0 & python 2.7.13, hexo 3.2.2.
```
INFO  Start processing
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 19): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 20): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 21): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 22): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 23): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 24): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 25): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 26): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 27): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 28): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 29): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 30): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 31): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 32): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 33): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 34): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 35): TypeError: Path must be a string. Received undefined
(node:2240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 36): TypeError: Path must be a string. Received undefined
```

**Comment by coldnew** [comment]
Do you setup the `config.org.emacs` to specify emacs path ?

If  still error, can you test https://github.com/coldnew/hexo-org-example ? (see `_config.yml`)

**Comment by saccohuo** [comment]
@coldnew I configure the emacs path in `_config_yml` as follows.
```
# hexo-renderer-org
## Docs: https://github.com/coldnew/hexo-render-org
org:
  emacs: C:/emacs/bin/emacs.exe
  common: |
          #+OPTIONS: toc:nil num:nil
          #+BIND: org-html-postamble \"Last Updated %C.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"
  cachedir: ./hexo-org-cache/
  theme: tango-dark
```
However, after `hexo g`, there were some beeps in the terminal, then it stuck there, and nothing happened.

**Comment by saccohuo** [comment]
@coldnew I tried [hexo-org-example](https://github.com/coldnew/hexo-org-example), and got the same result.

**Comment by coldnew** [comment]
mmm...... (｡ŏ_ŏ)

**Comment by coldnew** [comment]
@saccohuo Maybe you can add `debug: true` in you _config.yml to see if there's some output in stdout.

like this:

```yaml
# hexo-renderer-org
## Docs: https://github.com/coldnew/hexo-render-org
org:
  emacs: C:/emacs/bin/emacs.exe
  common: |
          #+OPTIONS: toc:nil num:nil
          #+BIND: org-html-postamble \"Last Updated %C.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"
  cachedir: ./hexo-org-cache/
  theme: tango-dark
  debug: true
```

In Linux/MacOSX, it will show something like following, so I can get a little debug info (not really helpful actually....)

<img width="795" alt="screen shot 2017-03-05 at 4 55 31 pm" src="https://cloud.githubusercontent.com/assets/39703/23585902/936717da-01c4-11e7-963c-c3cd0b9362c2.png">

I still need some effort to make emacs output the useful debugging information (#4) and test this under windows's ci (#5).
