### ISSUE TITLE
Add windows ci support 

### ISSUE THREAD

**Issue by coldnew** [coldnew/hexo-renderer-org#5]
https://ci.appveyor.com is CI for windows, add support to it

**Comment by coldnew** [comment]
Currently I create a `test-appveyor` to test windows ci with appveyor, after all test passed I'll merge back to current branch.

**Comment by coldnew** [comment]
The `appveyor.yml` file contains following information, however currently source still test failed under windows (time-out).

```yaml
clone_depth: 5

platform:
  - x86
  - x64

install:
  - node --version
  - npm --version
  - npm install
  - npm install -g cross-env
  - cinst emacs
  - emacs --version
  - where emacs

test_script:
  - cross-env NODE_ENV=test npm test

# Don't actually build.
build: off

cache:
  # local npm modules
  - node_modules -> package.json
```
